### ISSUE TITLE
Remove internal copy of Path#strip_prefix when 1.7 is stable

### ISSUE THREAD

**Issue by mcasper** [sgrif/diesel#183]
Specific issue for a FIXME per #173 

As of b1a215bd906039e2f4fa7e1af6259acd0f06129a, this FIXME is located here: https://github.com/sgrif/diesel/blob/master/diesel_cli/src/main.rs#L289

**Comment by sgrif** [comment]
Permalink: https://github.com/sgrif/diesel/blob/b1a215b/diesel_cli/src/main.rs#L289

**Comment by SoftwareWarlock** [comment]
Just to be clear, [`relative_from`](https://doc.rust-lang.org/std/path/struct.Path.html#method.relative_from) isn't being used because it's marked unstable (rust-lang/rust#23284), so once 1.7 is stable we should replace `strip_prefix` with [`Path::strip_prefix`](http://doc.rust-lang.org/nightly/std/path/struct.Path.html#method.strip_prefix)?

**Comment by mcasper** [comment]
Resolved by #230
