### ISSUE TITLE
sqlite connection error? (title updated)

### ISSUE THREAD

**Issue by yohanesu75** [sgrif/diesel#224]
Hi! First of all, thanks for great job!

How can I change to sqlite backend? I can't find any documentation about this.

**Comment by yohanesu75** [comment]
Ok, so just specifying a file as DATABASE_URL "diesel setup" and "diesel migration run" generates a database correctly but when I try the write_posts/read_posts (which works with pgsql) I get connection error:

[mirama@PC1-13-0006 diesel_demo$ cargo run --bin write_posts
     Running `target/debug/write_posts`
thread '<main>' panicked at 'Error connecting to /home/mirama/dev/diesel_demo/diesel_demo.sqlite: BadConnection("missing \"=\" after \"/home/mirama/dev/diesel_demo/diesel_demo.sqlite\" in connection info string\n")', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Process didn't exit successfully: `target/debug/write_posts` (exit code: 101)

**Comment by yohanesu75** [comment]
Oh I see.. I have to use different API for sqlite :) That brings us to the next problem. infer_schema!() is not implemented for sqlite. What is the way to solve this with sqlite?

**Comment by mcasper** [comment]
Hi @yohanesu75! You can definitely use a sqlite backend.

The CLI figures out what backend to use based on your DATABASE_URL, which is why it correctly used SQLite.

I'm pretty certain that the getting started demo is written all using Postgres, so a lot of it won't be compatible. It looks like you figured out to use the `SqliteConnection` struct instead of `PgConnection`, but you're correct, the `infer_schema` macro doesn't work for SQLite yet. I'm not entirely sure if `infer_table_from_schema(table)` works for SQLite, but I believe it doesn't work yet either. Instead you'll have to use the `table!` macro for each of your tables.

http://sgrif.github.io/diesel/diesel/macro.table!.html

**Comment by sgrif** [comment]
You need to call `table!` directly for SQLite at the moment.

**Comment by yohanesu75** [comment]
Thanks!
