### ISSUE TITLE
diesel_cli does not compile in travis container

### ISSUE THREAD

**Issue by jgillich** [sgrif/diesel#238]
Installing `diesel_cli` with cargo on `nightly` and `nightly-2016-03-11`:
```
undefined reference to `sqlite3_errstr'
```
https://travis-ci.org/jgillich/mp/jobs/116882725

I've tried installing `libsqlite3-dev`, does not help. No idea what is going on here, it works witth `sudo: required` for some reason...

**Comment by mcasper** [comment]
It looks like you're using postgres, so you should be able to work around this with 
```
cargo install diesel_cli --no-default-features --features postgres
```

Unfortunately diesel_cli by default compiles all the different connection types, which requires those backends to be installed. Still working on a way around this so that `cargo install diesel_cli` will always _just work_.

**Comment by jgillich** [comment]
What exactly would I have to install? I've added `libsqlite3-dev`, is there anything that would be needed?

I do use postgres because sqlite isn't fully implemented yet, but I do plan on using both in the future.

**Comment by mcasper** [comment]
`libsqlite3-dev` should be plenty, I think the `sudo: required` was the real ticket. (Vaguely) According to Travis docs, it looks like that's required to install any packages: `Allows use of sudo (e.g., for installing apt packages)`. 

However, it looks like we don't even install sqlite in our .travis.yml, we just have `sudo: required`, so that may be all you need.

**Comment by jgillich** [comment]
No, you can set `addons.apt.packages` when you're using containers. Check the build log (`Installing APT Packages`), it was definitely installed. So yes, the issue is that diesel_cli only builds in VMs.

**Comment by mcasper** [comment]
Ah, good point. I'll investigate this tonight

**Comment by sgrif** [comment]
Travis uses an ancient version of SQLite and you have to go through contortions to get it to work (see our travis.yml's history). However, the "update SQLite" issue on the travis package whitelist repo was recently closed, so they may have fixed it.

**Comment by sgrif** [comment]
> What exactly would I have to install?

Any version of libsqlite that is more recent than 2012
