### ISSUE TITLE
diesel setup doesn't work with some postgres URIs

### ISSUE THREAD

**Issue by voidxnull** [sgrif/diesel#247]
For example, I need to specify a username and password, so I've created an  .env file containing:
`DATABASE_URL=postgres://dev:password@localhost/my_db`

When I run `diesel setup` it panics with:
```
Creating database: my_db
thread '<main>' panicked at 'FATAL:  database "dev" does not exist
', /home/user/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.3/src/main.rs:235
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by mcasper** [comment]
Sorry about that!

Turns out that when dropping/creating a database, we connect to the user's DATABASE_URL minus the database, so if a user is supplied, we would connect to `postgres://user@localhost`, which postgres interprets as us wanting to connect to the `user` database as well.

Anyways, I pushed up a fix here: https://github.com/sgrif/diesel/pull/248
