### ISSUE TITLE
diesel_codegen depends on old version of diesel

### ISSUE THREAD

**Issue by tari** [sgrif/diesel#273]
I think somebody forgot to bump the version of the `diesel` dependency in `diesel_codegen` when releasing version 0.6, since it currently depends on 0.5.0. I'm not sure what the effects of such a thing would be, but probably nothing good and possibly confusing errors.

**Comment by sgrif** [comment]
> I think somebody forgot

Heh. I appreciate politely avoiding calling out my dumb mistake. 🙉 🙈 🙊

**Comment by sgrif** [comment]
Interestingly, I think the effects of this would be relatively minor. The version of Diesel that codegen uses wouldn't affect the code that it generates. Really the only thing that CLI and Codegen are affected by from Diesel is the Connection, which didn't have any changes to it in 0.6. Either way, we should point at the latest version because it's silly not to.
