### ISSUE TITLE
MySQL support in 0.x

### ISSUE THREAD

**Issue by e-oz** [sgrif/diesel#31]
I've [read](https://medium.com/@sgrif/announcing-diesel-a-safe-extensible-orm-and-query-builder-for-rust-fdf57966a16c#.xquzpvgda) you are going to add support of other databases only after 1.0, but differences between Postgre and MySQL are not so big, so please consider to support MySQL in 0.x. Then it will be well-tested for 1.0 :)

**Comment by sgrif** [comment]
I've updated my post to be less specific about the timeline for supporting other databases. It definitely makes sense to do pre-1.0 if possible, as it's unlikely to be something I can add without some amount of breaking API changes. However, I don't want to commit to any specific timeline.

I'm going to close this, as I've take the only actionable response to this I can.

As a side-note, since I haven't documented this anywhere, when we support MySQL, we'll still be following Postgres' semantics for a "correct query". So mixing aggregate and non-aggregate expressions will fail to compile, as will comparing a string with an integer (AKA [please dump my database](https://twitter.com/sgrif/status/656167420290199553)), etc.
