### ISSUE TITLE
Implement diesel Expression for more types

### ISSUE THREAD

**Issue by lephyrius** [sgrif/diesel#80]
``` 
error: the trait `diesel::expression::Expression` is not implemented for the type `u64` 
```
I got this error.
I solved it with this:
```rust
let game = games.filter(id.eq(params.find("id").unwrap().as_u64().unwrap() as i32 )).first(&connection);
```
This is a bit ugly. Could there be more types supported than just i32?
Any other suggestion than moving this cast to a function?

**Comment by sgrif** [comment]
All integer types are supported for use where appropriate. Unfortunately, the error messages can sometimes be unhelpful due to https://github.com/rust-lang/rust/issues/28894. What's allowed here is based on the type of `id`. It seems likely that your column is of type `Integer` or `Serial`, which are both 32 bit signed integers. You can't write `32bit_column.eq(1i64)`. For `BigInteger`, you can use 64 bit integers as well. However keep in mind that this type is also signed, and you can only use `i64` not `u64`. PostgreSQL does not have an unsigned integer type.

If my assumptions about your app are incorrect, let me know and I'll re-open.

**Comment by JohnMH** [comment]
Why is there no "sql type" for unsigned integers? In MySQL, for example, it is perfectly valid to have an `INT UNSIGNED`.

**Comment by weiznich** [comment]
@JohnMH See #1561 for unsigned integers in MySQL
